# Generated by Django 3.2.3 on 2021-07-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
